### ISSUE TITLE
Cannot find a valid RSS feed

### ISSUE THREAD

**Issue by brianspiering** [thomasballinger/posts#5]
I would like to subscribe to your blog. Feedly can't find a RSS feed. 

It would be awesome if there was a RSS feed for your blog.

see: https://feedly.com/i/discover/sources/search/feed/http%3A%2F%2Fballingt.com

**Comment by thomasballinger** [comment]
I've got a feed at http://ballingt.com/index.xml, do you know if there's a naming convention I'm not following that is preventing feedly from finding it? When I enter that it comes up.

**Comment by brianspiering** [comment]
Thanks - That works. 

I don't why I was getting that error.
